language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
notifications:
  webhooks:
    urls:
      - https://webhooks.trou.pe/e/89a3434745244f30dafc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
